// <auto-generated />
using System;
using FinansalAnaliz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinansalAnaliz.Migrations
{
    [DbContext(typeof(FinansalAnalizDbContext))]
    [Migration("20260529085257_FinansalVeriDuyguAlanlariEkle")]
    partial class FinansalVeriDuyguAlanlariEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinansalAnaliz.Models.Anomali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinansalVeriID")
                        .HasColumnType("int");

                    b.Property<double>("GuvenSkoru")
                        .HasColumnType("float");

                    b.Property<decimal>("IslemTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<decimal>("OrtalamaTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SapmaYuzdesi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TespitTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FinansalVeriID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Anomaliler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.DuyguKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duygu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("GuvenSkoru")
                        .HasColumnType("real");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("MetinDuygusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciID");

                    b.ToTable("DuyguKayitlari");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.FinansalVeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Duygu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyguNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("GuvenSkoru")
                        .HasColumnType("real");

                    b.Property<string>("IslemTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IslemTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kanal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("MetinDuygusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KategoriID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("FinansalVeriler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MlKategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.KategoriAnahtarKelime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnahtarKelime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriID");

                    b.ToTable("KategoriAnahtarKelimeler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Oneri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OneriTipi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Oneriler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Anomali", b =>
                {
                    b.HasOne("FinansalAnaliz.Models.FinansalVeri", "FinansalVeri")
                        .WithMany()
                        .HasForeignKey("FinansalVeriID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinansalAnaliz.Models.Kategori", "Kategori")
                        .WithMany("Anomaliler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinansalAnaliz.Models.Kullanici", "Kullanici")
                        .WithMany("Anomaliler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FinansalVeri");

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.DuyguKaydi", b =>
                {
                    b.HasOne("FinansalAnaliz.Models.Kullanici", "Kullanici")
                        .WithMany("DuyguKayitlari")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.FinansalVeri", b =>
                {
                    b.HasOne("FinansalAnaliz.Models.Kategori", "Kategori")
                        .WithMany("FinansalVeriler")
                        .HasForeignKey("KategoriID");

                    b.HasOne("FinansalAnaliz.Models.Kullanici", "Kullanici")
                        .WithMany("FinansalVeriler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.KategoriAnahtarKelime", b =>
                {
                    b.HasOne("FinansalAnaliz.Models.Kategori", "Kategori")
                        .WithMany("AnahtarKelimeler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Oneri", b =>
                {
                    b.HasOne("FinansalAnaliz.Models.Kullanici", "Kullanici")
                        .WithMany("Oneriler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Kategori", b =>
                {
                    b.Navigation("AnahtarKelimeler");

                    b.Navigation("Anomaliler");

                    b.Navigation("FinansalVeriler");
                });

            modelBuilder.Entity("FinansalAnaliz.Models.Kullanici", b =>
                {
                    b.Navigation("Anomaliler");

                    b.Navigation("DuyguKayitlari");

                    b.Navigation("FinansalVeriler");

                    b.Navigation("Oneriler");
                });
#pragma warning restore 612, 618
        }
    }
}
